name: Update Docs

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'docs/**'
      - 'workflows/**'
    tags-ignore:
      - '*'

permissions:
  contents: write

jobs:
  update-docs:
    name: 'Update Docs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout for CI ğŸ›ï¸'
        uses: actions/checkout@v4
      - name: 'Push Docs to Github Wiki ğŸ“„ï¸'
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: 'docs'